/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const  WoodenFence = (props) => {
  const { nodes, materials } = useGLTF("/assets/models/woodenFence/woodenFence.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WoodenFence.geometry}
        material={nodes.WoodenFence.material}
      />
    </group>
  );
}
export default WoodenFence;
useGLTF.preload("/assets/models/woodenFence/woodenFence.glb");
